apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: "{{ .Values.namespace.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          volumeMounts:
              - name: jenkins-data
                mountPath: /var/jenkins_home
      volumes:
          - name: jenkins-data
            persistentVolumeClaim:
                claimName: jenkins-pv-claim
