apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---



apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  APP_NAME: "MyApp"
  LOG_LEVEL: "debug"

---

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DB_USER: YWRtaW4=        # "admin"
  DB_PASSWORD: c2VjcmV0    # "secret"

---

